### ISSUE TITLE
Map My India for flutter

### ISSUE THREAD

**Issue by DeepakKanyanRor** [MapmyIndia/mapmyindia-rest-api#4]
Can you give some example of Map My India in Flutter?

**Comment by kunalbharti** [comment]
Flutter support is part of MapmyIndia's roadmap. Since this is more of a policy decision, closing this issue.
For more details, request to start a conversation with @MapmyIndia-Maps  directly via their [support email](apisupport@mapmyindia.com).

**Comment by 22shubh22** [comment]
We are waiting, flutter community is big, and growing support for flutter will definitely increase MapMyIndia's reputation.

**Comment by 7thHokage** [comment]
> We are waiting, flutter community is big, and growing support for flutter will definitely increase MapMyIndia's reputation.

bro can u pls make an example for Map My India in FLutter

**Comment by kunalbharti** [comment]
MapmyIndia has recently released its first cut map SDK for flutter.
Please see: https://github.com/MapmyIndia/flutter-mapmyindia-gl
There is still a lot of work to be done on it, but this is an initial release which should give basic functionalities.
🙂

**Comment by 7thHokage** [comment]
I am really really T

**Comment by 7thHokage** [comment]
thank u sooo muchhhh
really Thank u soo muchh
